### PR TITLE
feat: support .tsx extension

### PR DESCRIPTION
**Pull request by targos**
This allows to load files that use JSX syntax.

For example, this enables loading and rendering React components in Adonis.

### CODE REVIEW

**Comment by thetutlage** [comment]
Is that all we need to render tsx? Or do we need any transformers too?

**Comment by targos** [comment]
That's all we need. TypeScript knows JSX by default. It just requires a separate extension because of syntax ambiguities.

**Comment by targos** [comment]
To be clear, if I add this line manually in node_modules, and if I add `compilerOptions: { jsx: 'react' }` to my tsconfig.json, this is what happens:

For a file named `resources/react/App.tsx`, with the contents: 
```ts
import React from 'react';

export default function App(props: {name: string}) {
  return <div>Hello {props.name}</div>
}
```

Imports like `import App from '../resources/react/App';` just work and the cache contains a file in `resources-react-App/ca0287f83e.js` with:

```
"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const react_1 = __importDefault(require("react"));
function App(props) {
    return react_1.default.createElement("div", null,
        "Hello ",
        props.name);
}
exports.default = App;
```

**Comment by targos** [comment]
I added a commit that executes Prettier to make the tests pass.

**Comment by thetutlage** [comment]
Thanks 😄

**Pull request merged**
